# Set the latest golang base image:
FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy program files:
COPY . .

# Download dependencies:
RUN go mod download

# Build server:
RUN go build -o app .

# Expose server port:
EXPOSE 7000

# Run the server:
CMD ["./app"]