// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	file, err := os.Create("js.go")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	var appjs []byte
	if appjs, err = ioutil.ReadFile("src/appjs"); err != nil {
		panic(err)
	}

	fmt.Fprintln(file, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(file, "package appjs")
	fmt.Fprintln(file)
	fmt.Fprintln(file, "const appjs = `")
	fmt.Fprintf(file, "%s", appjs)
	fmt.Fprintln(file, "`")
}
