package main

// Code generated by go generate; DO NOT EDIT.

const goappJS = `const etag = '{{.ETag}}'

self.addEventListener('install', function (e) {
  console.log('intalling goapp worker', etag)
  self.skipWaiting()

  e.waitUntil(
    caches.open('goapp').then(function (cache) {
      return cache.addAll([
        {{range .Paths}}'{{.}}',
        {{end}}'/'
      ])
    })
  )
})

self.addEventListener('activate', event => {
  console.log('goapp worker', etag, 'is activated')
})

self.addEventListener('fetch', event => {
  event.respondWith(
    caches
      .match(event.request)
      .then(response => {
        return response || fetch(event.request)
      })
  )
})
`

const manifest = `{
    "short_name": "{{.ShortName}}",
    "name": "{{.Name}}",
    "icons": [
        {
            "src": "{{.Icon}}-192.png",
            "type": "image/png",
            "sizes": "192x192"
        },
        {
            "src": "{{.Icon}}-512.png",
            "type": "image/png",
            "sizes": "512x512"
        }
    ],
    "start_url": "{{.StartURL}}",
    "background_color": "{{.BackgroundColor}}",
    "display": "{{.Display}}",
    "scope": "{{.Scope}}",
    "orientation": "{{.Orientation}}",
    "theme_color": "{{.ThemeColor}}"
}`
