// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	file, err := os.Create("template.go")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	var template []byte
	if template, err = ioutil.ReadFile("page.html"); err != nil {
		panic(err)
	}

	fmt.Fprintln(file, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(file, "package html")
	fmt.Fprintln(file)
	fmt.Fprintln(file, "const pageTemplate = `")
	fmt.Fprintf(file, "%s", template)
	fmt.Fprintln(file, "`")
}
